In [1]:
import pandas as pd
import seaborn as sns

In [3]:
loan=pd.read_csv("C:/Users/trupti bovlekar/Downloads/Python_projects/Python_projects/Loan_data_analysis_project/Loan_dataset.csv")
loan

,Loan ID,Customer ID,Loan Status,Current Loan Amount,Term,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,14dd8831-6af5-400b-83ec-68e61888a048,981165ec-3274-42f5-a3b4-d104041a9ca9,Fully Paid,445412.0,Short Term,709.0,1167493.0,8 years,Home Mortgage,Home Improvements,5214.74,17.2,NaN,6.0,1.0,228190.0,416746.0,1.0,0.0
1,4771cc26-131a-45db-b5aa-537ea4ba5342,2de017a3-2e01-49cb-a581-08169e83be29,Fully Paid,262328.0,Short Term,NaN,NaN,10+ years,Home Mortgage,Debt Consolidation,33295.98,21.1,8.0,35.0,0.0,229976.0,850784.0,0.0,0.0
2,4eed4e6a-aa2f-4c91-8651-ce984ee8fb26,5efb2b2b-bf11-4dfd-a572-3761a2694725,Fully Paid,99999999.0,Short Term,741.0,2231892.0,8 years,Own Home,Debt Consolidation,29200.53,14.9,29.0,18.0,1.0,297996.0,750090.0,0.0,0.0
3,77598f7b-32e7-4e3b-a6e5-06ba0d98fe8a,e777faab-98ae-45af-9a86-7ce5b33b1011,Fully Paid,347666.0,Long Term,721.0,806949.0,3 years,Own Home,Debt Consolidation,8741.90,12.0,NaN,9.0,0.0,256329.0,386958.0,0.0,0.0
4,d4062e70-befa-4995-8643-a0de73938182,81536ad9-5ccf-4eb8-befb-47a4d608658e,Fully Paid,176220.0,Short Term,NaN,NaN,5 years,Rent,Debt Consolidation,20639.70,6.1,NaN,15.0,0.0,253460.0,427174.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100509,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100511,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100513,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
loan.columns

Index(['Loan ID', 'Customer ID', 'Loan Status', 'Current Loan Amount', 'Term',
       'Credit Score', 'Annual Income', 'Years in current job',
       'Home Ownership', 'Purpose', 'Monthly Debt', 'Years of Credit History',
       'Months since last delinquent', 'Number of Open Accounts',
       'Number of Credit Problems', 'Current Credit Balance',
       'Maximum Open Credit', 'Bankruptcies', 'Tax Liens'],
      dtype='object')

In [7]:
# 1.What is the average current loan amount for each loan status?
# Group by 'Loan Status' and calculate the mean of 'Current Loan Amount'

loan.groupby('Loan Status')['Current Loan Amount'].mean()

Loan Status
Charged Off    3.249752e+05
Fully Paid     1.510694e+07
Name: Current Loan Amount, dtype: float64

In [11]:
# 2. How does the credit score vary with the annual income?
loan[['Credit Score','Annual Income']].var()

Credit Score     2.176816e+06
Annual Income    1.169340e+12
dtype: float64

In [15]:
# 3. Is there a correlation between the number of open accounts and the current credit balance?
 
loan[['Number of Open Accounts','Current Credit Balance']].corr()

                         Number of Open Accounts  Current Credit Balance
Number of Open Accounts                 1.000000                0.228136
Current Credit Balance                  0.228136                1.000000

In [17]:
# 4. What is the distribution of credit scores across different home ownership types?
loan.groupby('Home Ownership')['Credit Score'].describe()

,count,mean,std,min,25%,50%,75%,max
Home Ownership,,,,,,,,
HaveMortgage,185.0,957.194595,1218.111959,663.0,703.0,719.0,735.0,7510.0
Home Mortgage,39089.0,1045.553992,1411.256479,585.0,706.0,725.0,742.0,7510.0
Own Home,7480.0,1087.634626,1501.576825,585.0,704.0,723.0,740.0,7510.0
Rent,34092.0,1110.082160,1540.661569,585.0,704.0,723.0,739.0,7510.0

In [21]:
# 5. How does the annual income differ for different purposes of loans?

loan.groupby('Purpose')['Annual Income'].describe()

,count,mean,std,min,25%,50%,75%,max
Purpose,,,,,,,,
Business Loan,1275.0,1.591963e+06,1.047181e+06,182818.0,911040.50,1342103.0,1911675.50,9338880.0
Buy House,565.0,1.495251e+06,1.086381e+06,214434.0,842517.00,1183073.0,1763390.00,7677501.0
Buy a Car,1024.0,1.220353e+06,7.442786e+05,135071.0,713336.00,1045636.5,1517568.00,6296334.0
Debt Consolidation,63314.0,1.362464e+06,1.079726e+06,76627.0,854658.00,1170210.0,1634988.00,165557393.0
Educational Expenses,82.0,1.071051e+06,8.076369e+05,81092.0,485953.50,914574.5,1317417.25,3752880.0
Home Improvements,4720.0,1.667437e+06,1.194598e+06,173793.0,977132.00,1384558.5,1947205.50,19019000.0
Medical Bills,921.0,1.409286e+06,9.529750e+05,189734.0,814549.00,1191072.0,1676465.00,9163985.0
Other,2642.0,1.348516e+06,1.044702e+06,106533.0,771295.50,1121817.0,1613798.25,18316380.0
Take a Trip,476.0,1.219899e+06,7.642818e+05,152475.0,741703.00,1055003.5,1497024.25,6796224.0
major_purchase,282.0,1.430753e+06,1.488982e+06,244682.0,762888.00,1114065.0,1650753.25,14975610.0
moving,125.0,1.591375e+06,1.855030e+06,200032.0,763458.00,1104071.0,1773479.00,17896176.0
other,5017.0,1.286008e+06,1.026819e+06,144267.0,756352.00,1074659.0,1534592.00,28095300.0
renewable_energy,8.0,1.473740e+06,6.796896e+05,668192.0,1195522.75,1516466.0,1558551.00,2888969.0
small_business,234.0,1.547456e+06,1.045103e+06,272289.0,940495.25,1332812.0,1812077.50,9439200.0
vacation,73.0,1.155290e+06,8.020623e+05,365598.0,656963.00,874760.0,1331463.00,5262962.0
wedding,88.0,1.464233e+06,9.886829e+05,456646.0,894182.75,1206272.0,1755438.50,6620208.0

In [23]:
# 6. What is the average monthly debt for each term (short-term vs. long-term)?

# Group by Term and calculate mean of Monthly Debt
loan.groupby('Term')['Monthly Debt'].mean()

Term
Long Term     21585.664968
Short Term    17274.158442
Name: Monthly Debt, dtype: float64

In [27]:
# 7. Is there a relationship between years of credit history and current credit balance?

loan[['Years of Credit History','Current Credit Balance']].corr()

                         Years of Credit History  Current Credit Balance
Years of Credit History                  1.00000                 0.20847
Current Credit Balance                   0.20847                 1.00000

In [29]:
# 8. How does the credit score vary with years in the current job?
loan.groupby('Years in current job')['Credit Score'].var()

Years in current job
1 year       2.427774e+06
10+ years    2.070920e+06
2 years      2.111050e+06
3 years      2.182079e+06
4 years      1.959840e+06
5 years      2.070745e+06
6 years      2.316885e+06
7 years      2.429288e+06
8 years      2.115297e+06
9 years      2.187997e+06
< 1 year     2.159927e+06
Name: Credit Score, dtype: float64

In [31]:
# 9. What is the relationship between number of credit problems and number of open accounts?
loan[['Number of Credit Problems','Number of Open Accounts']].corr()

                           Number of Credit Problems  Number of Open Accounts
Number of Credit Problems                   1.000000                -0.013995
Number of Open Accounts                    -0.013995                 1.000000

In [33]:
# 10. What is the distribution of annual income across different loan statuses?
loan.groupby('Loan Status')['Annual Income'].describe()

,count,mean,std,min,25%,50%,75%,max
Loan Status,,,,,,,,
Charged Off,17210.0,1.267790e+06,1.506251e+06,76627.0,778743.50,1085812.0,1507578.75,165557393.0
Fully Paid,63636.0,1.408157e+06,9.315770e+05,81092.0,865853.75,1213026.5,1694952.00,36475440.0

In [35]:
# 11. Is there a correlation between the current loan amount and the number of open accounts?
loan[['Current Loan Amount','Number of Open Accounts']].corr()

                         Current Loan Amount  Number of Open Accounts
Current Loan Amount                 1.000000                 0.001478
Number of Open Accounts             0.001478                 1.000000

In [37]:
# 12. How does the monthly debt vary with the years of credit history?

loan[['Monthly Debt','Years of Credit History']].var()

Monthly Debt               1.482304e+08
Years of Credit History    4.921477e+01
dtype: float64

In [39]:
# 13. What is the average annual income for each purpose of loan?

# Group by Purpose and calculate mean of Annual Income
loan.groupby('Purpose')['Annual Income'].mean()

Purpose
Business Loan           1.591963e+06
Buy House               1.495251e+06
Buy a Car               1.220353e+06
Debt Consolidation      1.362464e+06
Educational Expenses    1.071051e+06
Home Improvements       1.667437e+06
Medical Bills           1.409286e+06
Other                   1.348516e+06
Take a Trip             1.219899e+06
major_purchase          1.430753e+06
moving                  1.591375e+06
other                   1.286008e+06
renewable_energy        1.473740e+06
small_business          1.547456e+06
vacation                1.155290e+06
wedding                 1.464233e+06
Name: Annual Income, dtype: float64

In [41]:
# 14. How does the credit score vary with the number of credit problems?

loan.groupby('Number of Credit Problems')[['Credit Score']].var()

                           Credit Score
Number of Credit Problems
0.0                        2.189587e+06
1.0                        2.089538e+06
2.0                        2.281750e+06
3.0                        1.398355e+06
4.0                        2.618680e+06
5.0                        3.326562e+06
6.0                        2.573725e+06
7.0                        3.699524e+02
8.0                        4.033333e+01
9.0                        5.780000e+02
10.0                                NaN
11.0                       0.000000e+00
12.0                                NaN
15.0                                NaN

In [45]:
# 15. Is there a correlation between the number of credit problems and the current credit balance?
loan[['Number of Credit Problems','Current Credit Balance']].corr()

                           Number of Credit Problems  Current Credit Balance
Number of Credit Problems                   1.000000               -0.112516
Current Credit Balance                     -0.112516                1.000000

In [47]:
# 16. What is the distribution of current loan amounts across different home ownership types?
loan.groupby('Home Ownership')['Current Loan Amount'].describe()

,count,mean,std,min,25%,50%,75%,max
Home Ownership,,,,,,,,
HaveMortgage,214.0,1.366169e+07,3.426380e+07,10802.0,65252.0,116435.0,216271.0,99999999.0
Home Mortgage,48410.0,1.212491e+07,3.216712e+07,21472.0,217321.5,350999.0,561946.0,99999999.0
Own Home,9182.0,1.152623e+07,3.151952e+07,21472.0,172771.5,283536.0,493669.0,99999999.0
Rent,42194.0,1.138362e+07,3.137940e+07,11242.0,157366.0,261712.0,440473.0,99999999.0

In [49]:
# 17. How does the annual income vary with the years in the current job?

loan.groupby('Years in current job')['Annual Income'].var()

Years in current job
1 year       8.322965e+11
10+ years    1.944282e+12
2 years      8.579576e+11
3 years      7.637958e+11
4 years      7.314122e+11
5 years      8.009341e+11
6 years      8.974986e+11
7 years      8.178949e+11
8 years      8.452256e+11
9 years      9.509406e+11
< 1 year     8.123298e+11
Name: Annual Income, dtype: float64

In [51]:
# 18. Is there a correlation between the current loan amount and the monthly debt?
loan[['Current Loan Amount','Monthly Debt']].corr()

                     Current Loan Amount  Monthly Debt
Current Loan Amount             1.000000     -0.006643
Monthly Debt                   -0.006643      1.000000

In [53]:
# 19. What is the average monthly debt for each home ownership type?
# Group by Home Ownership and calculate mean of Monthly Debt
loan.groupby('Home Ownership')['Monthly Debt'].mean()

Home Ownership
HaveMortgage     18541.776822
Home Mortgage    21072.059467
Own Home         17060.082101
Rent             15796.777284
Name: Monthly Debt, dtype: float64

In [55]:
# 20. How does the credit score vary with the number of open accounts?
loan[['Number of Open Accounts','Credit Score']].var()

Number of Open Accounts    2.509880e+01
Credit Score               2.176816e+06
dtype: float64

In [57]:
# 21. What is the distribution of credit scores across different loan statuses?
loan.groupby('Loan Status')['Credit Score'].describe()

,count,mean,std,min,25%,50%,75%,max
Loan Status,,,,,,,,
Charged Off,17210.0,2402.296862,2826.692993,585.0,705.0,730.0,6500.0,7510.0
Fully Paid,63636.0,717.889874,27.221750,585.0,705.0,723.0,739.0,751.0

In [59]:
# 22. Is there a correlation between the current loan amount and the years of credit history?
loan[['Current Loan Amount','Years of Credit History']].corr()

                         Current Loan Amount  Years of Credit History
Current Loan Amount                 1.000000                 0.019282
Years of Credit History             0.019282                 1.000000

In [62]:
#23.How does the monthly debt vary with the number of credit problems? 
loan.groupby('Number of Credit Problems')['Monthly Debt'].var()

Number of Credit Problems
0.0     1.549349e+08
1.0     9.375118e+07
2.0     1.162055e+08
3.0     2.496895e+08
4.0     1.927077e+08
5.0     1.824749e+08
6.0     1.555993e+08
7.0     1.657217e+08
8.0     8.229946e+03
9.0     2.937936e+08
10.0    3.395910e+07
11.0    0.000000e+00
12.0             NaN
15.0             NaN
Name: Monthly Debt, dtype: float64

In [64]:
# 24. What is the average current loan amount for each purpose of loan?
# Group by Purpose and calculate mean of Current Loan Amount

loan.groupby('Purpose')['Current Loan Amount'].mean()

Purpose
Business Loan           7.837789e+06
Buy House               1.106036e+07
Buy a Car               1.414682e+07
Debt Consolidation      1.180683e+07
Educational Expenses    1.428536e+07
Home Improvements       1.252117e+07
Medical Bills           1.179902e+07
Other                   1.253627e+07
Take a Trip             1.111667e+07
major_purchase          1.298956e+07
moving                  1.350072e+07
other                   1.059243e+07
renewable_energy        1.975534e+05
small_business          9.484232e+06
vacation                7.058680e+06
wedding                 1.760299e+07
Name: Current Loan Amount, dtype: float64

In [66]:
#25.How does the credit score vary with the current credit balance? 
loan[['Credit Score','Current Credit Balance']].var()

Credit Score              2.176816e+06
Current Credit Balance    1.415046e+11
dtype: float64

In [68]:
#26.Is there a correlation between the annual income and the current credit balance? 
loan[['Annual Income','Current Credit Balance']].corr()

                        Annual Income  Current Credit Balance
Annual Income                 1.00000                 0.31234
Current Credit Balance        0.31234                 1.00000

In [70]:
#27.What is the distribution of annual income across different terms (short-term vs. long-term)? 
loan.groupby('Term')['Annual Income'].describe()

,count,mean,std,min,25%,50%,75%,max
Term,,,,,,,,
Long Term,23106.0,1.525574e+06,9.254852e+05,153178.0,985036.00,1326466.0,1800824.75,30838995.0
Short Term,57740.0,1.319332e+06,1.132423e+06,76627.0,787222.25,1127536.0,1584486.00,165557393.0

In [72]:
#28.How does the credit score vary with the number of credit problems? 
loan[['Credit Score','Number of Credit Problems']].var()

Credit Score                 2.176816e+06
Number of Credit Problems    2.330041e-01
dtype: float64

In [74]:
#29.Is there a correlation between the current loan amount and the number of credit problems? 
loan[['Current Loan Amount','Number of Credit Problems']].corr()

                           Current Loan Amount  Number of Credit Problems
Current Loan Amount                   1.000000                  -0.002795
Number of Credit Problems            -0.002795                   1.000000

In [76]:
#30.What is the relationship between the number of open accounts and the years of credit history?
loan[['Number of Open Accounts','Years of Credit History']].corr()

                         Number of Open Accounts  Years of Credit History
Number of Open Accounts                 1.000000                 0.132349
Years of Credit History                 0.132349                 1.000000